[variables]
SPACY_WARNING_IGNORE = "W008"

[phases.setup]
nixPkgs = ["python313", "python313Packages.pip"]

[phases.install]
cmds = [
  "python3.13 -m pip install -r requirements.txt",
  "python3.13 -m spacy download en_core_web_lg",
  "python3.13 -m spacy download de_core_news_lg",
  "python3.13 scripts/generate_test_pdfs.py",
  "python3.13 scripts/generate_extra_pdfs.py"
]

[phases.build]
cmds = []

[start]
cmd = "python3.13 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
